presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.14.3
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"


  - name: thoth-mypy-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/mypy
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.14.3
          command:
            - "/bin/run-mypy"
            - "."
            - --ignore-missing-imports
            - --exclude
            - "docs/|tasks/|tests/|setup.py|thamos/swagger_client/|examples/"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

  - name: thoth-pytest-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pytest
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.14.3
          command:
            - "/bin/run-pytest"
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "2Gi"
              cpu: "500m"
