host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: ubi8
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: pipfile-requirements
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - fridex
        - sesheta
        - mayaCostantini
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
