# coding: utf-8

"""
    Thoth User API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.6.0-dev
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from thamos.swagger_client.configuration import Configuration


class Build(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'base_image': 'str',
        'build_log': 'BuildBuildLog',
        'output_image': 'str'
    }

    attribute_map = {
        'base_image': 'base_image',
        'build_log': 'build_log',
        'output_image': 'output_image'
    }

    def __init__(self, base_image=None, build_log=None, output_image=None, local_vars_configuration=None):  # noqa: E501
        """Build - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._base_image = None
        self._build_log = None
        self._output_image = None
        self.discriminator = None

        self.base_image = base_image
        if build_log is not None:
            self.build_log = build_log
        self.output_image = output_image

    @property
    def base_image(self):
        """Gets the base_image of this Build.  # noqa: E501

        Name of base image used by the s2i build.   # noqa: E501

        :return: The base_image of this Build.  # noqa: E501
        :rtype: str
        """
        return self._base_image

    @base_image.setter
    def base_image(self, base_image):
        """Sets the base_image of this Build.

        Name of base image used by the s2i build.   # noqa: E501

        :param base_image: The base_image of this Build.  # noqa: E501
        :type: str
        """

        self._base_image = base_image

    @property
    def build_log(self):
        """Gets the build_log of this Build.  # noqa: E501


        :return: The build_log of this Build.  # noqa: E501
        :rtype: BuildBuildLog
        """
        return self._build_log

    @build_log.setter
    def build_log(self, build_log):
        """Sets the build_log of this Build.


        :param build_log: The build_log of this Build.  # noqa: E501
        :type: BuildBuildLog
        """

        self._build_log = build_log

    @property
    def output_image(self):
        """Gets the output_image of this Build.  # noqa: E501

        Name of output image - can also specify remote registry to pull image from.   # noqa: E501

        :return: The output_image of this Build.  # noqa: E501
        :rtype: str
        """
        return self._output_image

    @output_image.setter
    def output_image(self, output_image):
        """Sets the output_image of this Build.

        Name of output image - can also specify remote registry to pull image from.   # noqa: E501

        :param output_image: The output_image of this Build.  # noqa: E501
        :type: str
        """

        self._output_image = output_image

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Build):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Build):
            return True

        return self.to_dict() != other.to_dict()
