#
# This default Thoth configuration file placed in a root of a repo. Please adjust values listed below.

host: test.thoth-station.ninja
tls_verify: false

recommendation_type: stable
requirements_format: pipenv

runtime_environments:
  - name: "fedora:29"
    # Operating system for which the recommendations should be created:
    operating_system:
      name: fedora
      version: "29"
    recommendation_type: stable
